### ISSUE TITLE
Set requests and limits for k8s

### ISSUE THREAD

**Issue by ahutterTA** [uber/fiber#12]
It appears that only `limits` is set. Our admissions controller requires both `requests` and `limits`.

Could `requests` be set to the same values as `limits`? https://github.com/uber/fiber/blob/master/fiber/kubernetes_backend.py#L78

**Comment by calio** [comment]
From https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1ResourceRequirements.md
> Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value.

Is there a reason why both `requests` and `limits` need to be set?

**Comment by ahutterTA** [comment]
🤦 it does the right thing. Closing.
