### ISSUE TITLE
Page not found at docs

### ISSUE THREAD

**Issue by luancaarvalho** [uber/fiber#47]
In the platform and backends session after the kubernetes topic we have: 
![image](https://user-images.githubusercontent.com/34407796/110258163-eedd8080-7f7f-11eb-91fd-975d18f1d401.png)

But after click in the "here" link we get 404 error :
![image](https://user-images.githubusercontent.com/34407796/110258197-17657a80-7f80-11eb-97dc-1bac91416c20.png)

**Comment by calio** [comment]
Hi @luancaarvalho , thanks for reporting. Should have been fixed by now.
